#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use Librarian\Provider\ContentServiceProvider;
use Librarian\Provider\DevtoServiceProvider;

$app = new App(require __DIR__ . '/config.php');
$app->setSignature('Run "librarian help" for commands help.');
$app->addService('content', new ContentServiceProvider());
$app->addService('devto', new DevtoServiceProvider());

$app->runCommand($argv);
