#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use Miniweb\Provider\TwigServiceProvider;

$app = new App(require __DIR__ . '/config.php');
$app->addService('twig', new TwigServiceProvider());
$app->runCommand($argv);
